services:
  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_container
    ports:
      - "5050:5050"
    working_dir: /app
    command: bash run.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - flask-app
